[tool.poetry]
name = "cvgen-sqlite"
version = "0.1.4"
description = "CV Generator with SQLite"
authors = ["Marcel-Jan Krijgsman <cvgenerator@marcel-jan.eu>"]
readme = "README.md"
packages = [{include = "cvgen_sqlite", from = "src"}]

[tool.poetry.dependencies]
python = "^3.11"
streamlit = "^1.41.1"
weasyprint = "^63.1"
streamlit-sortables = "^0.2.0"
deepl = "^1.21.0"
python-dotenv = "^1.0.1"
idna = "3.7"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
