-- Engels
INSERT INTO Countries
 (CountryId, Alpha2Code, Alpha3Code, CountryName, Nationality, LanguageId)
VALUES
('4', 'AF', 'AFG', 'Afghanistan', 'Afghan', 2),
('248', 'AX', 'ALA', 'Åland Islands', 'Åland Island', 2),
('8', 'AL', 'ALB', 'Albania', 'Albanian', 2),
('12', 'DZ', 'DZA', 'Algeria', 'Algerian', 2),
('16', 'AS', 'ASM', 'American Samoa', 'American Samoan', 2),
('20', 'AD', 'AND', 'Andorra', 'Andorran', 2),
('24', 'AO', 'AGO', 'Angola', 'Angolan', 2),
('660', 'AI', 'AIA', 'Anguilla', 'Anguillan', 2),
('10', 'AQ', 'ATA', 'Antarctica', 'Antarctic', 2),
('28', 'AG', 'ATG', 'Antigua and Barbuda', 'Antiguan or Barbudan', 2),
('32', 'AR', 'ARG', 'Argentina', 'Argentine', 2),
('51', 'AM', 'ARM', 'Armenia', 'Armenian', 2),
('533', 'AW', 'ABW', 'Aruba', 'Aruban', 2),
('36', 'AU', 'AUS', 'Australia', 'Australian', 2),
('40', 'AT', 'AUT', 'Austria', 'Austrian', 2),
('31', 'AZ', 'AZE', 'Azerbaijan', 'Azerbaijani, Azeri', 2),
('44', 'BS', 'BHS', 'Bahamas', 'Bahamian', 2),
('48', 'BH', 'BHR', 'Bahrain', 'Bahraini', 2),
('50', 'BD', 'BGD', 'Bangladesh', 'Bangladeshi', 2),
('52', 'BB', 'BRB', 'Barbados', 'Barbadian', 2),
('112', 'BY', 'BLR', 'Belarus', 'Belarusian', 2),
('56', 'BE', 'BEL', 'Belgium', 'Belgian', 2),
('84', 'BZ', 'BLZ', 'Belize', 'Belizean', 2),
('204', 'BJ', 'BEN', 'Benin', 'Beninese, Beninois', 2),
('60', 'BM', 'BMU', 'Bermuda', 'Bermudian, Bermudan', 2),
('64', 'BT', 'BTN', 'Bhutan', 'Bhutanese', 2),
('68', 'BO', 'BOL', 'Bolivia (Plurinational State of)', 'Bolivian', 2),
('535', 'BQ', 'BES', 'Bonaire, Sint Eustatius and Saba', 'Bonaire', 2),
('70', 'BA', 'BIH', 'Bosnia and Herzegovina', 'Bosnian or Herzegovinian', 2),
('72', 'BW', 'BWA', 'Botswana', 'Motswana, Botswanan', 2),
('74', 'BV', 'BVT', 'Bouvet Island', 'Bouvet Island', 2),
('76', 'BR', 'BRA', 'Brazil', 'Brazilian', 2),
('86', 'IO', 'IOT', 'British Indian Ocean Territory', 'BIOT', 2),
('96', 'BN', 'BRN', 'Brunei Darussalam', 'Bruneian', 2),
('100', 'BG', 'BGR', 'Bulgaria', 'Bulgarian', 2),
('854', 'BF', 'BFA', 'Burkina Faso', 'Burkinabé', 2),
('108', 'BI', 'BDI', 'Burundi', 'Burundian', 2),
('132', 'CV', 'CPV', 'Cabo Verde', 'Cabo Verdean', 2),
('116', 'KH', 'KHM', 'Cambodia', 'Cambodian', 2),
('120', 'CM', 'CMR', 'Cameroon', 'Cameroonian', 2),
('124', 'CA', 'CAN', 'Canada', 'Canadian', 2),
('136', 'KY', 'CYM', 'Cayman Islands', 'Caymanian', 2),
('140', 'CF', 'CAF', 'Central African Republic', 'Central African', 2),
('148', 'TD', 'TCD', 'Chad', 'Chadian', 2),
('152', 'CL', 'CHL', 'Chile', 'Chilean', 2),
('156', 'CN', 'CHN', 'China', 'Chinese', 2),
('162', 'CX', 'CXR', 'Christmas Island', 'Christmas Island', 2),
('166', 'CC', 'CCK', 'Cocos (Keeling) Islands', 'Cocos Island', 2),
('170', 'CO', 'COL', 'Colombia', 'Colombian', 2),
('174', 'KM', 'COM', 'Comoros', 'Comoran, Comorian', 2),
('178', 'CG', 'COG', 'Congo (Republic of the)', 'Congolese', 2),
('180', 'CD', 'COD', 'Congo (Democratic Republic of the)', 'Congolese', 2),
('184', 'CK', 'COK', 'Cook Islands', 'Cook Island', 2),
('188', 'CR', 'CRI', 'Costa Rica', 'Costa Rican', 2),
('384', 'CI', 'CIV', 'Côte d''Ivoire', 'Ivorian', 2),
('191', 'HR', 'HRV', 'Croatia', 'Croatian', 2),
('192', 'CU', 'CUB', 'Cuba', 'Cuban', 2),
('531', 'CW', 'CUW', 'Curaçao', 'Curaçaoan', 2),
('196', 'CY', 'CYP', 'Cyprus', 'Cypriot', 2),
('203', 'CZ', 'CZE', 'Czech Republic', 'Czech', 2),
('208', 'DK', 'DNK', 'Denmark', 'Danish', 2),
('262', 'DJ', 'DJI', 'Djibouti', 'Djiboutian', 2),
('212', 'DM', 'DMA', 'Dominica', 'Dominican', 2),
('214', 'DO', 'DOM', 'Dominican Republic', 'Dominican', 2),
('218', 'EC', 'ECU', 'Ecuador', 'Ecuadorian', 2),
('818', 'EG', 'EGY', 'Egypt', 'Egyptian', 2),
('222', 'SV', 'SLV', 'El Salvador', 'Salvadoran', 2),
('226', 'GQ', 'GNQ', 'Equatorial Guinea', 'Equatorial Guinean, Equatoguinean', 2),
('232', 'ER', 'ERI', 'Eritrea', 'Eritrean', 2),
('233', 'EE', 'EST', 'Estonia', 'Estonian', 2),
('231', 'ET', 'ETH', 'Ethiopia', 'Ethiopian', 2),
('238', 'FK', 'FLK', 'Falkland Islands (Malvinas)', 'Falkland Island', 2),
('234', 'FO', 'FRO', 'Faroe Islands', 'Faroese', 2),
('242', 'FJ', 'FJI', 'Fiji', 'Fijian', 2),
('246', 'FI', 'FIN', 'Finland', 'Finnish', 2),
('250', 'FR', 'FRA', 'France', 'French', 2),
('254', 'GF', 'GUF', 'French Guiana', 'French Guianese', 2),
('258', 'PF', 'PYF', 'French Polynesia', 'French Polynesian', 2),
('260', 'TF', 'ATF', 'French Southern Territories', 'French Southern Territories', 2),
('266', 'GA', 'GAB', 'Gabon', 'Gabonese', 2),
('270', 'GM', 'GMB', 'Gambia', 'Gambian', 2),
('268', 'GE', 'GEO', 'Georgia', 'Georgian', 2),
('276', 'DE', 'DEU', 'Germany', 'German', 2),
('288', 'GH', 'GHA', 'Ghana', 'Ghanaian', 2),
('292', 'GI', 'GIB', 'Gibraltar', 'Gibraltar', 2),
('300', 'GR', 'GRC', 'Greece', 'Greek, Hellenic', 2),
('304', 'GL', 'GRL', 'Greenland', 'Greenlandic', 2),
('308', 'GD', 'GRD', 'Grenada', 'Grenadian', 2),
('312', 'GP', 'GLP', 'Guadeloupe', 'Guadeloupe', 2),
('316', 'GU', 'GUM', 'Guam', 'Guamanian, Guambat', 2),
('320', 'GT', 'GTM', 'Guatemala', 'Guatemalan', 2),
('831', 'GG', 'GGY', 'Guernsey', 'Channel Island', 2),
('324', 'GN', 'GIN', 'Guinea', 'Guinean', 2),
('624', 'GW', 'GNB', 'Guinea-Bissau', 'Bissau-Guinean', 2),
('328', 'GY', 'GUY', 'Guyana', 'Guyanese', 2),
('332', 'HT', 'HTI', 'Haiti', 'Haitian', 2),
('334', 'HM', 'HMD', 'Heard Island and McDonald Islands', 'Heard Island or McDonald Islands', 2),
('336', 'VA', 'VAT', 'Vatican City State', 'Vatican', 2),
('340', 'HN', 'HND', 'Honduras', 'Honduran', 2),
('344', 'HK', 'HKG', 'Hong Kong', 'Hong Kong, Hong Kongese', 2),
('348', 'HU', 'HUN', 'Hungary', 'Hungarian, Magyar', 2),
('352', 'IS', 'ISL', 'Iceland', 'Icelandic', 2),
('356', 'IN', 'IND', 'India', 'Indian', 2),
('360', 'ID', 'IDN', 'Indonesia', 'Indonesian', 2),
('364', 'IR', 'IRN', 'Iran', 'Iranian, Persian', 2),
('368', 'IQ', 'IRQ', 'Iraq', 'Iraqi', 2),
('372', 'IE', 'IRL', 'Ireland', 'Irish', 2),
('833', 'IM', 'IMN', 'Isle of Man', 'Manx', 2),
('376', 'IL', 'ISR', 'Israel', 'Israeli', 2),
('380', 'IT', 'ITA', 'Italy', 'Italian', 2),
('388', 'JM', 'JAM', 'Jamaica', 'Jamaican', 2),
('392', 'JP', 'JPN', 'Japan', 'Japanese', 2),
('832', 'JE', 'JEY', 'Jersey', 'Channel Island', 2),
('400', 'JO', 'JOR', 'Jordan', 'Jordanian', 2),
('398', 'KZ', 'KAZ', 'Kazakhstan', 'Kazakhstani, Kazakh', 2),
('404', 'KE', 'KEN', 'Kenya', 'Kenyan', 2),
('296', 'KI', 'KIR', 'Kiribati', 'I-Kiribati', 2),
('408', 'KP', 'PRK', 'Korea (Democratic People''s Republic of)', 'North Korean', 2),
('410', 'KR', 'KOR', 'Korea (Republic of)', 'South Korean', 2),
('414', 'KW', 'KWT', 'Kuwait', 'Kuwaiti', 2),
('417', 'KG', 'KGZ', 'Kyrgyzstan', 'Kyrgyzstani, Kyrgyz, Kirgiz, Kirghiz', 2),
('418', 'LA', 'LAO', 'Lao People''s Democratic Republic', 'Lao, Laotian', 2),
('428', 'LV', 'LVA', 'Latvia', 'Latvian', 2),
('422', 'LB', 'LBN', 'Lebanon', 'Lebanese', 2),
('426', 'LS', 'LSO', 'Lesotho', 'Basotho', 2),
('430', 'LR', 'LBR', 'Liberia', 'Liberian', 2),
('434', 'LY', 'LBY', 'Libya', 'Libyan', 2),
('438', 'LI', 'LIE', 'Liechtenstein', 'Liechtenstein', 2),
('440', 'LT', 'LTU', 'Lithuania', 'Lithuanian', 2),
('442', 'LU', 'LUX', 'Luxembourg', 'Luxembourg, Luxembourgish', 2),
('446', 'MO', 'MAC', 'Macao', 'Macanese, Chinese', 2),
('807', 'MK', 'MKD', 'Macedonia (the former Yugoslav Republic of)', 'Macedonian', 2),
('450', 'MG', 'MDG', 'Madagascar', 'Malagasy', 2),
('454', 'MW', 'MWI', 'Malawi', 'Malawian', 2),
('458', 'MY', 'MYS', 'Malaysia', 'Malaysian', 2),
('462', 'MV', 'MDV', 'Maldives', 'Maldivian', 2),
('466', 'ML', 'MLI', 'Mali', 'Malian, Malinese', 2),
('470', 'MT', 'MLT', 'Malta', 'Maltese', 2),
('584', 'MH', 'MHL', 'Marshall Islands', 'Marshallese', 2),
('474', 'MQ', 'MTQ', 'Martinique', 'Martiniquais, Martinican', 2),
('478', 'MR', 'MRT', 'Mauritania', 'Mauritanian', 2),
('480', 'MU', 'MUS', 'Mauritius', 'Mauritian', 2),
('175', 'YT', 'MYT', 'Mayotte', 'Mahoran', 2),
('484', 'MX', 'MEX', 'Mexico', 'Mexican', 2),
('583', 'FM', 'FSM', 'Micronesia (Federated States of)', 'Micronesian', 2),
('498', 'MD', 'MDA', 'Moldova (Republic of)', 'Moldovan', 2),
('492', 'MC', 'MCO', 'Monaco', 'Monégasque, Monacan', 2),
('496', 'MN', 'MNG', 'Mongolia', 'Mongolian', 2),
('499', 'ME', 'MNE', 'Montenegro', 'Montenegrin', 2),
('500', 'MS', 'MSR', 'Montserrat', 'Montserratian', 2),
('504', 'MA', 'MAR', 'Morocco', 'Moroccan', 2),
('508', 'MZ', 'MOZ', 'Mozambique', 'Mozambican', 2),
('104', 'MM', 'MMR', 'Myanmar', 'Burmese', 2),
('516', 'NA', 'NAM', 'Namibia', 'Namibian', 2),
('520', 'NR', 'NRU', 'Nauru', 'Nauruan', 2),
('524', 'NP', 'NPL', 'Nepal', 'Nepali, Nepalese', 2),
('528', 'NL', 'NLD', 'Netherlands', 'Dutch', 2),
('540', 'NC', 'NCL', 'New Caledonia', 'New Caledonian', 2),
('554', 'NZ', 'NZL', 'New Zealand', 'New Zealand, NZ', 2),
('558', 'NI', 'NIC', 'Nicaragua', 'Nicaraguan', 2),
('562', 'NE', 'NER', 'Niger', 'Nigerien', 2),
('566', 'NG', 'NGA', 'Nigeria', 'Nigerian', 2),
('570', 'NU', 'NIU', 'Niue', 'Niuean', 2),
('574', 'NF', 'NFK', 'Norfolk Island', 'Norfolk Island', 2),
('580', 'MP', 'MNP', 'Northern Mariana Islands', 'Northern Marianan', 2),
('578', 'NO', 'NOR', 'Norway', 'Norwegian', 2),
('512', 'OM', 'OMN', 'Oman', 'Omani', 2),
('586', 'PK', 'PAK', 'Pakistan', 'Pakistani', 2),
('585', 'PW', 'PLW', 'Palau', 'Palauan', 2),
('275', 'PS', 'PSE', 'Palestine, State of', 'Palestinian', 2),
('591', 'PA', 'PAN', 'Panama', 'Panamanian', 2),
('598', 'PG', 'PNG', 'Papua New Guinea', 'Papua New Guinean, Papuan', 2),
('600', 'PY', 'PRY', 'Paraguay', 'Paraguayan', 2),
('604', 'PE', 'PER', 'Peru', 'Peruvian', 2),
('608', 'PH', 'PHL', 'Philippines', 'Philippine, Filipino', 2),
('612', 'PN', 'PCN', 'Pitcairn', 'Pitcairn Island', 2),
('616', 'PL', 'POL', 'Poland', 'Polish', 2),
('620', 'PT', 'PRT', 'Portugal', 'Portuguese', 2),
('630', 'PR', 'PRI', 'Puerto Rico', 'Puerto Rican', 2),
('634', 'QA', 'QAT', 'Qatar', 'Qatari', 2),
('638', 'RE', 'REU', 'Réunion', 'Réunionese, Réunionnais', 2),
('642', 'RO', 'ROU', 'Romania', 'Romanian', 2),
('643', 'RU', 'RUS', 'Russian Federation', 'Russian', 2),
('646', 'RW', 'RWA', 'Rwanda', 'Rwandan', 2),
('652', 'BL', 'BLM', 'Saint Barthélemy', 'Barthélemois', 2),
('654', 'SH', 'SHN', 'Saint Helena, Ascension and Tristan da Cunha', 'Saint Helenian', 2),
('659', 'KN', 'KNA', 'Saint Kitts and Nevis', 'Kittitian or Nevisian', 2),
('662', 'LC', 'LCA', 'Saint Lucia', 'Saint Lucian', 2),
('663', 'MF', 'MAF', 'Saint Martin (French part)', 'Saint-Martinoise', 2),
('666', 'PM', 'SPM', 'Saint Pierre and Miquelon', 'Saint-Pierrais or Miquelonnais', 2),
('670', 'VC', 'VCT', 'Saint Vincent and the Grenadines', 'Saint Vincentian, Vincentian', 2),
('882', 'WS', 'WSM', 'Samoa', 'Samoan', 2),
('674', 'SM', 'SMR', 'San Marino', 'Sammarinese', 2),
('678', 'ST', 'STP', 'Sao Tome and Principe', 'São Toméan', 2),
('682', 'SA', 'SAU', 'Saudi Arabia', 'Saudi, Saudi Arabian', 2),
('686', 'SN', 'SEN', 'Senegal', 'Senegalese', 2),
('688', 'RS', 'SRB', 'Serbia', 'Serbian', 2),
('690', 'SC', 'SYC', 'Seychelles', 'Seychellois', 2),
('694', 'SL', 'SLE', 'Sierra Leone', 'Sierra Leonean', 2),
('702', 'SG', 'SGP', 'Singapore', 'Singaporean', 2),
('534', 'SX', 'SXM', 'Sint Maarten (Dutch part)', 'Sint Maarten', 2),
('703', 'SK', 'SVK', 'Slovakia', 'Slovak', 2),
('705', 'SI', 'SVN', 'Slovenia', 'Slovenian, Slovene', 2),
('90', 'SB', 'SLB', 'Solomon Islands', 'Solomon Island', 2),
('706', 'SO', 'SOM', 'Somalia', 'Somali, Somalian', 2),
('710', 'ZA', 'ZAF', 'South Africa', 'South African', 2),
('239', 'GS', 'SGS', 'South Georgia and the South Sandwich Islands', 'South Georgia or South Sandwich Islands', 2),
('728', 'SS', 'SSD', 'South Sudan', 'South Sudanese', 2),
('724', 'ES', 'ESP', 'Spain', 'Spanish', 2),
('144', 'LK', 'LKA', 'Sri Lanka', 'Sri Lankan', 2),
('729', 'SD', 'SDN', 'Sudan', 'Sudanese', 2),
('740', 'SR', 'SUR', 'Suriname', 'Surinamese', 2),
('744', 'SJ', 'SJM', 'Svalbard and Jan Mayen', 'Svalbard', 2),
('748', 'SZ', 'SWZ', 'Swaziland', 'Swazi', 2),
('752', 'SE', 'SWE', 'Sweden', 'Swedish', 2),
('756', 'CH', 'CHE', 'Switzerland', 'Swiss', 2),
('760', 'SY', 'SYR', 'Syrian Arab Republic', 'Syrian', 2),
('158', 'TW', 'TWN', 'Taiwan, Province of China', 'Chinese, Taiwanese', 2),
('762', 'TJ', 'TJK', 'Tajikistan', 'Tajikistani', 2),
('834', 'TZ', 'TZA', 'Tanzania, United Republic of', 'Tanzanian', 2),
('764', 'TH', 'THA', 'Thailand', 'Thai', 2),
('626', 'TL', 'TLS', 'Timor-Leste', 'Timorese', 2),
('768', 'TG', 'TGO', 'Togo', 'Togolese', 2),
('772', 'TK', 'TKL', 'Tokelau', 'Tokelauan', 2),
('776', 'TO', 'TON', 'Tonga', 'Tongan', 2),
('780', 'TT', 'TTO', 'Trinidad and Tobago', 'Trinidadian or Tobagonian', 2),
('788', 'TN', 'TUN', 'Tunisia', 'Tunisian', 2),
('792', 'TR', 'TUR', 'Turkey', 'Turkish', 2),
('795', 'TM', 'TKM', 'Turkmenistan', 'Turkmen', 2),
('796', 'TC', 'TCA', 'Turks and Caicos Islands', 'Turks and Caicos Island', 2),
('798', 'TV', 'TUV', 'Tuvalu', 'Tuvaluan', 2),
('800', 'UG', 'UGA', 'Uganda', 'Ugandan', 2),
('804', 'UA', 'UKR', 'Ukraine', 'Ukrainian', 2),
('784', 'AE', 'ARE', 'United Arab Emirates', 'Emirati, Emirian, Emiri', 2),
('826', 'GB', 'GBR', 'United Kingdom of Great Britain and Northern Ireland', 'British, UK', 2),
('581', 'UM', 'UMI', 'United States Minor Outlying Islands', 'American', 2),
('840', 'US', 'USA', 'United States of America', 'American', 2),
('858', 'UY', 'URY', 'Uruguay', 'Uruguayan', 2),
('860', 'UZ', 'UZB', 'Uzbekistan', 'Uzbekistani, Uzbek', 2),
('548', 'VU', 'VUT', 'Vanuatu', 'Ni-Vanuatu, Vanuatuan', 2),
('862', 'VE', 'VEN', 'Venezuela (Bolivarian Republic of)', 'Venezuelan', 2),
('704', 'VN', 'VNM', 'Vietnam', 'Vietnamese', 2),
('92', 'VG', 'VGB', 'Virgin Islands (British)', 'British Virgin Island', 2),
('850', 'VI', 'VIR', 'Virgin Islands (U.S.)', 'U.S. Virgin Island', 2),
('876', 'WF', 'WLF', 'Wallis and Futuna', 'Wallis and Futuna, Wallisian or Futunan', 2),
('732', 'EH', 'ESH', 'Western Sahara', 'Sahrawi, Sahrawian, Sahraouian', 2),
('887', 'YE', 'YEM', 'Yemen', 'Yemeni', 2),
('894', 'ZM', 'ZMB', 'Zambia', 'Zambian', 2),
('716', 'ZW', 'ZWE', 'Zimbabwe', 'Zimbabwean', 2);


-- Nederlands
INSERT INTO Countries
 (CountryId, Alpha2Code, Alpha3Code, CountryName, Nationality, LanguageId)
VALUES
('4', 'AF', 'AFG', 'Afghanistan', 'Afghaans', 1),
('248', 'AX', 'ALA', 'Åland-eilanden', 'Åland-eiland', 1),
('8', 'AL', 'ALB', 'Albanië', 'Albanees', 1),
('12', 'DZ', 'DZA', 'Algerije', 'Algerijn', 1),
('16', 'AS', 'ASM', 'Amerikaans-Samoa', 'Amerikaans-Samoaans', 1),
('20', 'AD', 'AND', 'Andorra', 'Andorreans', 1),
('24', 'AO', 'AGO', 'Angola', 'Angolaans', 1),
('660', 'AI', 'AIA', 'Anguilla', 'Anguillan', 1),
('10', 'AQ', 'ATA', 'Antarctica', 'Antarctica', 1),
('28', 'AG', 'ATG', 'Antigua en Barbuda', 'Antiguaan of Barbudan', 1),
('32', 'AR', 'ARG', 'Argentinië', 'Argentinië', 1),
('51', 'AM', 'ARM', 'Armenië', 'Armeens', 1),
('533', 'AW', 'ABW', 'Aruba', 'Aruban', 1),
('36', 'AU', 'AUS', 'Australië', 'Australisch', 1),
('40', 'AT', 'AUT', 'Oostenrijk', 'Oostenrijks', 1),
('31', 'AZ', 'AZE', 'Azerbeidzjan', 'Azerbeidzjaans, Azerbeidzjaans', 1),
('44', 'BS', 'BHS', 'Bahama''s', 'Bahamaans', 1),
('48', 'BH', 'BHR', 'Bahrein', 'Bahreinse', 1),
('50', 'BD', 'BGD', 'Bangladesh', 'Bangladesh', 1),
('52', 'BB', 'BRB', 'Barbados', 'Barbadiaans', 1),
('112', 'BY', 'BLR', 'Wit-Rusland', 'Wit-Russisch', 1),
('56', 'BE', 'BEL', 'België', 'Belgisch', 1),
('84', 'BZ', 'BLZ', 'Belize', 'Belizean', 1),
('204', 'BJ', 'BEN', 'Benin', 'Beninees, Beninois', 1),
('60', 'BM', 'BMU', 'Bermuda', 'Bermuda, Bermuda', 1),
('64', 'BT', 'BTN', 'Bhutan', 'Bhutanese', 1),
('68', 'BO', 'BOL', 'Bolivia (plurinationale staat)', 'Boliviaans', 1),
('535', 'BQ', 'BES', 'Bonaire, Sint Eustatius en Saba', 'Bonaire', 1),
('70', 'BA', 'BIH', 'Bosnië en Herzegovina', 'Bosnisch of Herzegovina', 1),
('72', 'BW', 'BWA', 'Botswana', 'Motswana, Botswana', 1),
('74', 'BV', 'BVT', 'Bouveteiland', 'Bouveteiland', 1),
('76', 'BR', 'BRA', 'Brazilië', 'Braziliaans', 1),
('86', 'IO', 'IOT', 'Britse Indische Oceaan Grondgebied', 'BIOT', 1),
('96', 'BN', 'BRN', 'Brunei Darussalam', 'Bruneian', 1),
('100', 'BG', 'BGR', 'Bulgarije', 'Bulgaars', 1),
('854', 'BF', 'BFA', 'Burkina Faso', 'Burkinabe', 1),
('108', 'BI', 'BDI', 'Burundi', 'Burundiaan', 1),
('132', 'CV', 'CPV', 'Kabo Verde', 'Kabo Verdean', 1),
('116', 'KH', 'KHM', 'Cambodja', 'Cambodjaans', 1),
('120', 'CM', 'CMR', 'Kameroen', 'Kameroen', 1),
('124', 'CA', 'CAN', 'Canada', 'Canadees', 1),
('136', 'KY', 'CYM', 'Kaaimaneilanden', 'Kaaimaneilanden', 1),
('140', 'CF', 'CAF', 'Centraal-Afrikaanse Republiek', 'Centraal-Afrika', 1),
('148 ', 'TD', 'TCD', 'Tsjaad', 'Tsjadisch', 1),
('152', 'CL', 'CHL', 'Chili', 'Chileens', 1),
('156', 'CN', 'CHN', 'China', 'Chinees', 1),
('162', 'CX', 'CXR', 'Christmaseiland', 'Christmaseiland', 1),
('166', 'CC', 'CCK', 'Cocos (Keeling) Eilanden', 'Cocos Eiland', 1),
('170', 'CO', 'COL', 'Colombia', 'Colombiaans', 1),
(' 174', 'KM', 'COM', 'Comoren', 'Comoraan, Comorees', 1),
('178', 'CG', 'COG', 'Congo (Republiek van de)', 'Congolese', 1),
('180', 'CD', 'COD', 'Congo (Democratische Republiek van de)', 'Congolese', 1),
('184', 'CK', 'COK', 'Cookeilanden', 'Cookeiland', 1),
('188', 'CR', 'CRI' , 'Costa Rica', 'Costa Ricaans', 1),
('384', 'CI', 'CIV', 'Ivoorkust', 'Ivoriaans', 1),
('191', 'HR', 'HRV', 'Kroatië', 'Kroatisch', 1),
('192', 'CU', 'CUB', 'Cuba', 'Cubaans', 1),
('531', 'CW', 'CUW ', 'Curaçao', 'Curaçaoaans', 1),
('196', 'CY', 'CYP', 'Cyprus', 'Cypriotisch', 1),
('203', 'CZ', 'CZE', 'Tsjechische Republiek', 'Tsjechisch', 2 ),
('208', 'DK', 'DNK', 'Denemarken', 'Deens', 1),
('262', 'DJ', 'DJI', 'Djibouti', 'Djiboutiaans', 1),
('212', 'DM', 'DMA', 'Dominica', 'Dominicaans', 1),
('214', 'DO', 'DOM', 'Dominicaanse Republiek', 'Dominicaans', 1),
( '218', 'EC', 'ECU', 'Ecuador', 'Ecuadoriaans', 1),
('818', 'EG', 'EGY', 'Egypte', 'Egyptisch', 1),
('222 ', 'SV', 'SLV', 'El Salvador', 'Salvadoraans', 1),
('226', 'GQ', 'GNQ', 'Equatoriaal-Guinea', 'Equatoriaal-Guinees, Equatoguineaans', 1),
('232', 'ER', 'ERI', 'Eritrea', 'Eritrese', 1),
('233', 'EE', 'EST', 'Estland', 'Ests', 1),
('231', 'ET', 'ETH', 'Ethiopië', 'Ethiopisch', 1),
('238', 'FK', 'FLK', 'Falklandeilanden (Malvinas)', 'Falklandeiland', 1),
('234', 'FO', 'FRO', 'Faeröer', 'Faeröer', 1),
('242', 'FJ', 'FJI', 'Fiji', 'Fijisch', 1),
('246', 'FI', 'FIN', 'Finland', 'Fins', 1),
('250', 'FR', 'FRA', 'Frankrijk', 'Frans', 1),
('254', 'GF', 'GUF', 'Frans-Guyana', ' Frans-Guyanees', 1),
('258', 'PF', 'PYF', 'Frans-Polynesië', 'Frans-Polynesisch', 1),
('260', 'TF', 'ATF', 'Franse Zuidelijke Gebieden ', 'Franse Zuidelijke Gebieden', 1),
('266', 'GA', 'GAB', 'Gabon', 'Gabonees', 1),
('270', 'GM', 'GMB', 'Gambia ', 'Gambiaans', 1),
('268', 'GE', 'GEO', 'Georgië', 'Georgisch', 1),
('276', 'DE', 'DEU', 'Duitsland', 'Duits', 1),
('288', 'GH', 'GHA', 'Ghana', 'Ghanees', 1),
('292', 'GI', 'GIB', 'Gibraltar', 'Gibraltar', 1),
('300', 'GR', 'GRC', 'Griekenland', 'Grieks , Helleens', 1),
('304', 'GL', 'GRL', 'Groenland', 'Groenlands', 1),
('308', 'GD', 'GRD', 'Grenada', 'Grenadisch ', 1),
('312', 'GP', 'GLP', 'Guadeloupe', 'Guadeloupe', 1),
('316', 'GU', 'GUM', 'Guam', 'Guamaanse, Guambat ', 1),
('320', 'GT', 'GTM', 'Guatemala', 'Guatemalaans', 1),
('831', 'GG', 'GGY', 'Guernsey', 'Kanaaleiland', 1),
('324', 'GN', 'GIN', 'Guinea', 'Guinees', 1),
('624', 'GW', 'GNB', 'Guinee-Bissau', 'Bissau-Guinees', 1),
('328', 'GY', 'GUY', 'Guyana', 'Guyanese', 1),
('332', 'HT', 'HTI', 'Haïti', 'Haïtiaans', 1),
('334', 'HM', 'HMD', 'Heard- en McDonaldeilanden', 'Heard- of McDonaldeilanden', 1),
('336', 'VA', 'VAT', 'Vaticaanstad', 'Vaticaanstad', 1),
('340', 'HN', 'HND', 'Honduras', 'Honduraans', 1),
('344', 'HK', 'HKG', 'Hongkong', 'Hongkong, Hong Kongese', 1),
('348', 'HU', 'HUN', 'Hongarije', 'Hongaars, Magyaars', 1),
('352', 'IS', 'ISL', 'IJsland', 'IJslands', 1),
('356', 'IN', 'IND', 'India', 'Indiaas', 1),
('360', 'ID', 'IDN', 'Indonesië', 'Indonesisch', 1),
('364', 'IR', 'IRN', 'Iran', 'Iraans, Perzisch', 1),
('368', 'IQ', 'IRQ', 'Irak', 'Irakees', 1),
('372', 'IE', 'IRL', 'Ierland', 'Iers', 1),
('833', 'IM', 'IMN', 'Isle of Man', 'Manx', 1),
('376', 'IL', 'ISR', 'Israël', 'Israëlisch', 1),
('380', 'IT', 'ITA', 'Italië', 'Italiaans', 1),
('388', 'JM', 'JAM', 'Jamaica', 'Jamaicaans', 1),
('392', 'JP', 'JPN', 'Japan', 'Japans', 1),
('832', 'JE', 'JEY', 'Jersey', 'Kanaaleiland', 1),
('400', 'JO', 'JOR', 'Jordanië', 'Jordaans', 1),
('398', 'KZ', 'KAZ', 'Kazachstan', 'Kazachstani, Kazachs', 1),
('404', 'KE', 'KEN', 'Kenia', 'Keniaans', 1),
('296', 'KI', 'KIR', 'Kiribati', 'I-Kiribati', 1),
('408', 'KP', 'PRK', 'Korea (Democratische Volksrepubliek)', 'Noord-Koreaans', 1),
('410', 'KR', 'KOR', 'Korea (Republiek)', 'Zuid-Koreaans', 1),
('414', 'KW', 'KWT', 'Koeweit', 'Koeweit', 1),
('417', 'KG', 'KGZ', 'Kirgizië', 'Kirgizië, Kirgizisch, Kirgizisch, Kirgizisch', 1),
('418', 'LA', 'LAO', 'Democratische Volksrepubliek Laos', 'Laotiaans, Laotiaans', 1),
('428', 'LV', 'LVA', 'Letland', 'Lets', 1),
('422', 'LB', 'LBN', 'Libanon', 'Libanees', 1),
('426', 'LS', 'LSO', 'Lesotho', 'Basotho', 1),
('430', 'LR', 'LBR', 'Liberia', 'Liberiaans', 1),
('434', 'LY', 'LBY', 'Libië', 'Libisch', 1),
('438', 'LI', 'LIE', 'Liechtenstein', 'Liechtenstein', 1),
('440', 'LT', 'LTU', 'Litouwen', 'Litouws', 1),
('442', 'LU', 'LUX', 'Luxemburg', 'Luxemburg, Luxemburgs', 1),
('446', 'MO', 'MAC', 'Macau', 'Macanees, Chinees', 1),
('807', 'MK', 'MKD', 'Macedonië (de voormalige Joegoslavische Republiek)', 'Macedonië', 1),
('450', 'MG', 'MDG', 'Madagaskar', 'Malagasi', 1),
('454', 'MW', 'MWI', 'Malawi', 'Malawiaans', 1),
('458', 'MY', 'MYS', 'Maleisië', 'Maleisisch', 1),
('462', 'MV', 'MDV', 'Maldiven', 'Maldivisch', 1),
('466', 'ML', 'MLI', 'Mali', 'Malinees, Malinees', 1),
('470', 'MT', 'MLT', 'Malta', 'Maltees', 1),
('584', 'MH', 'MHL', 'Marshalleilanden', 'Marshallese', 1),
('474', 'MQ', 'MTQ', 'Martinique', 'Martiniquais, Martinicaan', 1),
('478', 'MR', 'MRT', 'Mauritanië', 'Mauritaans', 1),
('480', 'MU', 'MUS', 'Mauritius', 'Mauritiaans', 1),
('175', 'YT', 'MYT', 'Mayotte', 'Mahoran', 1),
('484', 'MX', 'MEX', 'Mexico', 'Mexicaans', 1),
('583', 'FM', 'FSM', 'Micronesië (Federale Staten van)', 'Micronesisch', 1),
('498', 'MD', 'MDA', 'Moldavië (Republiek van)', 'Moldavisch', 1),
('492', 'MC', 'MCO', 'Monaco', 'Monégasque, Monacan', 1),
('496', 'MN', 'MNG', 'Mongolië', 'Mongools', 1),
('499', 'ME', 'MNE', 'Montenegro', 'Montenegrijns', 1),
('500', 'MS', 'MSR', 'Montserrat', 'Montserratian', 1),
('504', 'MA', 'MAR', 'Marokko', 'Marokkaans', 1),
('508', 'MZ', 'MOZ', 'Mozambique', 'Mozambikaans', 1),
('104', 'MM', 'MMR', 'Myanmar', 'Birmees', 1),
('516', 'NA', 'NAM', 'Namibië', 'Namibisch', 1),
('520', 'NR', 'NRU', 'Nauru', 'Nauruaans', 1),
('524', 'NP', 'NPL', 'Nepal', 'Nepalees, Nepalees', 1),
('528', 'NL', 'NLD', 'Nederland', 'Nederlands', 1),
('540', 'NC', 'NCL', 'Nieuw-Caledonië', 'Nieuw-Caledonisch', 1),
('554', 'NZ', 'NZL', 'Nieuw-Zeeland', 'Nieuw-Zeeland, NZ', 1),
('558', 'NI', 'NIC', 'Nicaragua', 'Nicaraguaan', 1),
('562', 'NE', 'NER', 'Niger', 'Nigerien', 1),
('566', 'NG', 'NGA', 'Nigeria', 'Nigeriaanse', 1),
('570', 'NU', 'NIU', 'Niue', 'Niuean', 1),
('574', 'NF', 'NFK', 'Norfolkeiland', 'Norfolkeiland', 1),
('580', 'MP', 'MNP', 'Noordelijke Marianen', 'Noordelijke Marianen', 1),
('578', 'NO', 'NOR', 'Noorwegen', 'Noors', 1),
('512', 'OM', 'OMN', 'Oman', 'Omani', 1),
('586', 'PK', 'PAK', 'Pakistan', 'Pakistani', 1),
('585', 'PW', 'PLW', 'Palau', 'Palauan', 1),
('275', 'PS', 'PSE', 'Palestina, Staat van', 'Palestijns', 1),
('591', 'PA', 'PAN', 'Panama', 'Panamees', 1),
('598', 'PG', 'PNG', 'Papoea-Nieuw-Guinea', 'Papoea-Nieuw-Guinea, Papoea', 1),
('600', 'PY', 'PRY', 'Paraguay', 'Paraguayaans', 1),
('604', 'PE', 'PER', 'Peru', 'Peruviaans', 1),
('608', 'PH', 'PHL', 'Filipijnen', 'Filippijnen, Filipijns', 1),
('612', 'PN', 'PCN', 'Pitcairn', 'Pitcairneiland', 1),
('616', 'PL', 'POL', 'Polen', 'Pools', 1),
('620', 'PT', 'PRT', 'Portugal', 'Portugees', 1),
('630', 'PR', 'PRI', 'Puerto Rico', 'Puerto Ricaans', 1),
('634', 'QA', 'QAT', 'Qatar', 'Qatari', 1),
('638', 'RE', 'REU', 'Réunion', 'Réunionese, Réunionnais', 1),
('642', 'RO', 'ROU', 'Roemenië', 'Roemeens', 1),
('643', 'RU', 'RUS', 'Russische Federatie', 'Russisch', 1),
('646', 'RW', 'RWA', 'Rwanda', 'Rwandees', 1),
('652', 'BL', 'BLM', 'Saint Barthélemy', 'Barthélemois', 1),
('654', 'SH', 'SHN', 'Sint-Helena, Ascension en Tristan da Cunha', 'Sint-Helenian', 1),
('659', 'KN', 'KNA', 'Saint Kitts en Nevis', 'Kittitian of Nevisian', 1),
('662', 'LC', 'LCA', 'Saint Lucia', 'Saint Lucian', 1),
('663', 'MF', 'MAF', 'Saint Martin (Franse deel)', 'Saint-Martinoise', 1),
('666', 'PM', 'SPM', 'Saint Pierre en Miquelon', 'Saint-Pierrais of Miquelonnais', 1),
('670', 'VC', 'VCT', 'Saint Vincent en de Grenadines', 'Saint Vincentiaans, Vincentiaans', 1),
('882', 'WS', 'WSM', 'Samoa', 'Samoaans', 1),
('674', 'SM', 'SMR', 'San Marino', 'Sammarinees', 1),
('678', 'ST', 'STP', 'Sao Tomé en Principe', 'São Tomé', 1),
('682', 'SA', 'SAU', 'Saoedi-Arabië', 'Saoedi-Arabië', 1),
('686', 'SN', 'SEN', 'Senegal', 'Senegalese', 1),
('688', 'RS', 'SRB', 'Servië', 'Servisch', 1),
('690', 'SC', 'SYC', 'Seychellen', 'Seychellen', 1),
('694', 'SL', 'SLE', 'Sierra Leone', 'Sierra Leone', 1),
('702', 'SG', 'SGP', 'Singapore', 'Singaporees', 1),
('534', 'SX', 'SXM', 'Sint Maarten (Nederlands deel)', 'Sint Maarten', 1),
('703', 'SK', 'SVK', 'Slowakije', 'Slowaaks', 1),
('705', 'SI', 'SVN', 'Slovenië', 'Sloveens, Sloveens', 1),
('90', 'SB', 'SLB', 'Salomonseilanden', 'Salomonseiland', 1),
('706', 'SO', 'SOM', 'Somalië', 'Somalisch, Somalisch', 1),
('710', 'ZA', 'ZAF', 'Zuid-Afrika', 'Zuid-Afrikaans', 1),
('239', 'GS', 'SGS', 'Zuid Georgia en de Zuidelijke Sandwicheilanden', 'South Georgia of de Zuidelijke Sandwicheilanden', 1),
('728', 'SS', 'SSD', 'Zuid-Soedan', 'Zuid-Soedanees', 1),
('724', 'ES', 'ESP', 'Spanje', 'Spaans', 1),
('144', 'LK', 'LKA', 'Sri Lanka', 'Sri Lankaans', 1),
('729', 'SD', 'SDN', 'Soedan', 'Soedanees', 1),
('740', 'SR', 'SUR', 'Suriname', 'Surinaams', 1),
('744', 'SJ', 'SJM', 'Spitsbergen en Jan Mayen', 'Spitsbergen', 1),
('748', 'SZ', 'SWZ', 'Swaziland', 'Swazi', 1),
('752', 'SE', 'SWE', 'Zweden', 'Zweeds', 1),
('756', 'CH', 'CHE', 'Zwitserland', 'Zwitsers', 1),
('760', 'SY', 'SYR', 'Syrische Arabische Republiek', 'Syrisch', 1),
('158', 'TW', 'TWN', 'Taiwan, provincie China', 'Chinees, Taiwanees', 1),
('762', 'TJ', 'TJK', 'Tadzjikistan', 'Tadzjikistan', 1),
('834', 'TZ', 'TZA', 'Tanzania, Verenigde Republiek', 'Tanzanian', 1),
('764', 'TH', 'THA', 'Thailand', 'Thais', 1),
('626', 'TL', 'TLS', 'Timor-Leste', 'Timorees', 1),
('768', 'TG', 'TGO', 'Togo', 'Togolese', 1),
('772', 'TK', 'TKL', 'Tokelau', 'Tokelauan', 1),
('776', 'TO', 'TON', 'Tonga', 'Tongaans', 1),
('780', 'TT', 'TTO', 'Trinidad en Tobago', 'Trinidadisch of Tobagonisch', 1),
('788', 'TN', 'TUN', 'Tunesië', 'Tunesisch', 1),
('792', 'TR', 'TUR', 'Turkije', 'Turks', 1),
('795', 'TM', 'TKM', 'Turkmenistan', 'Turkmeens', 1),
('796', 'TC', 'TCA', 'Turks- en Caicoseilanden', 'Turks- en Caicoseilanden', 1),
('798', 'TV', 'TUV', 'Tuvalu', 'Tuvaluan', 1),
('800', 'UG', 'UGA', 'Oeganda', 'Oegandees', 1),
('804', 'UA', 'UKR', 'Oekraïne', 'Oekraïens', 1),
('784', 'AE', 'ARE', 'Verenigde Arabische Emiraten', 'Emirati, Emirian, Emiri', 1),
('826', 'GB', 'GBR', 'Verenigd Koninkrijk van Groot-Brittannië en Noord-Ierland', 'Brits, VK', 1),
('581', 'UM', 'UMI', 'kleine afgelegen eilanden van de Verenigde Staten', 'Amerikaans', 1),
('840', 'US', 'USA', 'Verenigde Staten van Amerika', 'Amerikaans', 1),
('858', 'UY', 'URY', 'Uruguay', 'Uruguayaan', 1),
('860', 'UZ', 'UZB', 'Oezbekistan', 'Oezbeeks, Oezbeeks', 1),
('548', 'VU', 'VUT', 'Vanuatu', 'Ni-Vanuatu, Vanuatuan', 1),
('862', 'VE', 'VEN', 'Venezuela (Bolivariaanse Republiek)', 'Venezolaans', 1),
('704', 'VN', 'VNM', 'Vietnam', 'Vietnamees', 1),
('92', 'VG', 'VGB', 'Virgin Islands (Brits)', 'British Virgin Island', 1),
('850', 'VI', 'VIR', 'Virgin Islands (U.S.)', 'U.S. Maagdeneiland', 1),
('876', 'WF', 'WLF', 'Wallis en Futuna', 'Wallis en Futuna, Wallisian of Futunan', 1),
('732', 'EH', 'ESH', 'Westelijke Sahara', 'Sahrawi, Sahrawi, Sahraouian', 1),
('887', 'YE', 'YEM', 'Jemen', 'Jemenitisch', 1),
('894', 'ZM', 'ZMB', 'Zambia', 'Zambiaans', 1),
('716', 'ZW', 'ZWE', 'Zimbabwe', 'Zimbabwean', 1);
